import type { Client, Dossier } from "@/types";

// ─── Clients ───────────────────────────────────────────────────────────────────

export const mockClients: Client[] = [
  {
    id: "cli-001",
    type: "physique",
    nom: "Benali",
    prenom: "Youssef",
    cin: "BE123456",
    telephone: "+212 6 61 23 45 67",
    email: "youssef.benali@gmail.com",
    adresse: "12 Rue Ibn Sina, Casablanca 20000",
    notes: "Client fidèle depuis 2022. Préfère être contacté par email.",
    createdAt: "2022-03-15",
  },
  {
    id: "cli-002",
    type: "physique",
    nom: "El Fassi",
    prenom: "Fatima",
    cin: "EF789012",
    telephone: "+212 6 62 34 56 78",
    email: "fatima.elfassi@hotmail.com",
    adresse: "45 Avenue Mohammed V, Rabat 10000",
    notes: "Affaire familiale complexe. Situation émotionnellement délicate.",
    createdAt: "2022-07-20",
  },
  {
    id: "cli-003",
    type: "morale",
    nom: "Maroc Textile SARL",
    prenom: "",
    cin: "",
    telephone: "+212 5 22 45 67 89",
    email: "contact@maroctextile.ma",
    adresse: "Zone Industrielle Sidi Bernoussi, Casablanca 20600",
    rc: "RC-CAS-78901",
    ice: "001234567000045",
    notes: "PME spécialisée dans l'export textile. Contrat annuel de conseil.",
    createdAt: "2021-11-05",
  },
  {
    id: "cli-004",
    type: "physique",
    nom: "Tazi",
    prenom: "Omar",
    cin: "TZ456789",
    telephone: "+212 6 63 45 67 89",
    email: "omar.tazi@gmail.com",
    adresse: "8 Rue Al Qods, Marrakech 40000",
    notes: "Litige foncier avec voisin. Dossier urgent.",
    createdAt: "2023-01-10",
  },
  {
    id: "cli-005",
    type: "physique",
    nom: "Chraibi",
    prenom: "Nadia",
    cin: "CH890123",
    telephone: "+212 6 64 56 78 90",
    email: "nadia.chraibi@yahoo.fr",
    adresse: "23 Boulevard Anfa, Casablanca 20050",
    notes: "Procédure de divorce en cours. Garde des enfants à régler.",
    createdAt: "2023-04-02",
  },
  {
    id: "cli-006",
    type: "morale",
    nom: "Immobilière Al Boraq SA",
    prenom: "",
    cin: "",
    telephone: "+212 5 37 67 89 01",
    email: "juridique@alboraq.ma",
    adresse: "Tour Rabat Business Center, Rabat 10100",
    rc: "RC-RAB-34567",
    ice: "002345678000012",
    notes: "Grand promoteur immobilier. Plusieurs dossiers en parallèle.",
    createdAt: "2021-06-18",
  },
  {
    id: "cli-007",
    type: "physique",
    nom: "Idrissi",
    prenom: "Hassan",
    cin: "ID234567",
    telephone: "+212 6 65 67 89 01",
    email: "hassan.idrissi@gmail.com",
    adresse: "67 Rue des Orangers, Fès 30000",
    notes: "Conflit commercial avec ex-associé. Demande de dommages-intérêts.",
    createdAt: "2022-09-14",
  },
  {
    id: "cli-008",
    type: "physique",
    nom: "Benkiran",
    prenom: "Samira",
    cin: "BK567890",
    telephone: "+212 6 66 78 90 12",
    email: "samira.benkiran@gmail.com",
    adresse: "15 Avenue Hassan II, Agadir 80000",
    notes: "Accident du travail. Salarié en arrêt maladie longue durée.",
    createdAt: "2023-06-28",
  },
  {
    id: "cli-009",
    type: "morale",
    nom: "Agro Atlas SARL",
    prenom: "",
    cin: "",
    telephone: "+212 5 24 56 78 90",
    email: "direction@agroatlas.ma",
    adresse: "Route d'Ouzoud, Azilal 22000",
    rc: "RC-AZI-12345",
    ice: "003456789000078",
    notes: "Coopérative agricole. Litige avec fournisseur d'engrais.",
    createdAt: "2023-02-19",
  },
  {
    id: "cli-010",
    type: "physique",
    nom: "Alaoui",
    prenom: "Karim",
    cin: "AL901234",
    telephone: "+212 6 67 89 01 23",
    email: "karim.alaoui@gmail.com",
    adresse: "3 Rue Docteur Veyre, Casablanca 20000",
    notes: "Affaire pénale. Présumé innocent. Représentation en appel.",
    createdAt: "2023-08-07",
  },
  {
    id: "cli-011",
    type: "physique",
    nom: "Zouhri",
    prenom: "Meryem",
    cin: "ZO345678",
    telephone: "+212 6 68 90 12 34",
    email: "meryem.zouhri@gmail.com",
    adresse: "90 Rue Khalid Ibn Walid, Casablanca 20100",
    notes: "Licenciement abusif. Demande de réintégration et d'indemnités.",
    createdAt: "2024-01-15",
  },
  {
    id: "cli-012",
    type: "morale",
    nom: "Tech Solutions Maroc SA",
    prenom: "",
    cin: "",
    telephone: "+212 5 22 90 12 34",
    email: "legal@techsolutions.ma",
    adresse: "Technopark Casablanca, Casablanca 20150",
    rc: "RC-CAS-56789",
    ice: "004567890000034",
    notes: "Startup tech. Besoin de conseil en droit commercial et RGPD.",
    createdAt: "2024-03-22",
  },
];

// ─── Dossiers (données embarquées) ────────────────────────────────────────────

export const mockDossiers: Dossier[] = [
  {
    id: "dos-001",
    numero: "DOS-2022-001",
    clientId: "cli-001",
    client: mockClients[0],
    partieAdverse: "Société Immobilière Al Wifaq",
    type: "civil",
    tribunal: "TPI Casablanca",
    statut: "en_cours",
    description: "Litige relatif à l'exécution d'un contrat de vente immobilière. Le client réclame la restitution de l'acompte versé suite à la résiliation unilatérale par le vendeur.",
    notes: [
      {
        id: "not-001-1",
        contenu: "Première consultation : le client dispose de toutes les preuves de paiement. Dossier solide.",
        createdAt: "2022-03-20",
        auteur: "Me. Rachid Amrani",
      },
      {
        id: "not-001-2",
        contenu: "Assignation déposée au greffe du TPI Casablanca. Numéro de rôle : 2022/1456.",
        createdAt: "2022-04-10",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-001-1",
        nom: "Contrat de vente.pdf",
        type: "contrat",
        taille: 245000,
        url: "/documents/dos-001/contrat-vente.pdf",
        createdAt: "2022-03-18",
      },
    ],
    audiences: [
      {
        id: "aud-001-2",
        dossierId: "dos-001",
        date: "2022-09-20",
        heure: "10:30",
        tribunal: "TPI Casablanca",
        salle: "Salle 4",
        type: "audience",
        statut: "terminee",
        notes: "Plaidoiries entendues. Mise en délibéré.",
      },
      {
        id: "aud-001-3",
        dossierId: "dos-001",
        date: "2026-05-14",
        heure: "09:00",
        tribunal: "TPI Casablanca",
        salle: "Salle 4",
        type: "delibere",
        statut: "programmee",
      },
    ],
    factures: [
      {
        id: "fac-001-1",
        numero: "FAC-2022-001",
        dossierId: "dos-001",
        clientId: "cli-001",
        lignes: [
          { id: "lig-001-1-1", description: "Consultation initiale", quantite: 1, prixUnitaire: 3000 },
          { id: "lig-001-1-2", description: "Rédaction et dépôt assignation", quantite: 1, prixUnitaire: 8000 },
        ],
        tva: 20,
        totalHT: 11000,
        totalTTC: 13200,
        statut: "payee",
        dateEmission: "2022-04-15",
        dateEcheance: "2022-05-15",
      },
    ],
    createdAt: "2022-03-15",
  },
  {
    id: "dos-002",
    numero: "DOS-2022-002",
    clientId: "cli-002",
    client: mockClients[1],
    partieAdverse: "El Fassi Mohammed (époux)",
    type: "famille",
    tribunal: "TPI Rabat",
    statut: "cloture",
    description: "Procédure de divorce par consentement mutuel. Règlement de la garde des enfants mineurs et de la pension alimentaire.",
    notes: [
      {
        id: "not-002-1",
        contenu: "Convention de divorce rédigée et acceptée par les deux parties. Audience de ratification prévue.",
        createdAt: "2022-09-05",
        auteur: "Me. Rachid Amrani",
      },
      {
        id: "not-002-2",
        contenu: "Jugement rendu. Garde des enfants attribuée à la mère, droit de visite bimensuel au père.",
        createdAt: "2022-11-30",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-002-1",
        nom: "Acte de mariage.pdf",
        type: "acte_etat_civil",
        taille: 156000,
        url: "/documents/dos-002/acte-mariage.pdf",
        createdAt: "2022-08-10",
      },
    ],
    audiences: [
      {
        id: "aud-002-2",
        dossierId: "dos-002",
        date: "2022-11-28",
        heure: "09:30",
        tribunal: "TPI Rabat",
        type: "prononce",
        statut: "terminee",
        notes: "Jugement prononcé conformément à la convention.",
      },
    ],
    factures: [
      {
        id: "fac-002-1",
        numero: "FAC-2022-008",
        dossierId: "dos-002",
        clientId: "cli-002",
        lignes: [
          { id: "lig-002-1-1", description: "Honoraires divorce par consentement mutuel", quantite: 1, prixUnitaire: 15000 },
        ],
        tva: 20,
        totalHT: 15000,
        totalTTC: 18000,
        statut: "payee",
        dateEmission: "2022-12-05",
        dateEcheance: "2022-12-20",
      },
    ],
    createdAt: "2022-08-01",
  },
  {
    id: "dos-003",
    numero: "DOS-2021-003",
    clientId: "cli-003",
    client: mockClients[2],
    partieAdverse: "Douanes Maroc — Bureau de Casablanca",
    type: "administratif",
    tribunal: "TA Casablanca",
    statut: "en_cours",
    description: "Recours contentieux contre une décision de saisie douanière de marchandises textiles. Contestation du bien-fondé de la saisie et demande de mainlevée.",
    notes: [
      {
        id: "not-003-1",
        contenu: "Les marchandises ont été saisies à tort selon le client. Documents d'import conformes.",
        createdAt: "2021-11-15",
        auteur: "Me. Rachid Amrani",
      },
      {
        id: "not-003-2",
        contenu: "Recours préalable rejeté par l'administration. Passage au contentieux judiciaire.",
        createdAt: "2022-01-08",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-003-1",
        nom: "Décision de saisie douanière.pdf",
        type: "decision_administrative",
        taille: 178000,
        url: "/documents/dos-003/decision-saisie.pdf",
        createdAt: "2021-11-10",
      },
    ],
    audiences: [
      {
        id: "aud-003-1",
        dossierId: "dos-003",
        date: "2022-03-10",
        heure: "10:00",
        tribunal: "TA Casablanca",
        type: "audience",
        statut: "terminee",
      },
      {
        id: "aud-003-2",
        dossierId: "dos-003",
        date: "2026-04-22",
        heure: "09:00",
        tribunal: "TA Casablanca",
        salle: "Chambre 2",
        type: "audience",
        statut: "programmee",
        notes: "Présentation du rapport d'expertise.",
      },
    ],
    factures: [
      {
        id: "fac-003-2",
        numero: "FAC-2023-012",
        dossierId: "dos-003",
        clientId: "cli-003",
        lignes: [
          { id: "lig-003-2-1", description: "Honoraires complémentaires — phase expertise", quantite: 1, prixUnitaire: 12000 },
        ],
        tva: 20,
        totalHT: 12000,
        totalTTC: 14400,
        statut: "en_retard",
        dateEmission: "2023-07-01",
        dateEcheance: "2023-08-01",
      },
    ],
    createdAt: "2021-11-05",
  },
  {
    id: "dos-004",
    numero: "DOS-2023-004",
    clientId: "cli-004",
    client: mockClients[3],
    partieAdverse: "Bennani Rachid (voisin)",
    type: "civil",
    tribunal: "TPI Marrakech",
    statut: "en_cours",
    description: "Litige foncier opposant deux propriétaires voisins. Contestation des limites de propriété et empiètement allégué sur la parcelle du client.",
    notes: [
      {
        id: "not-004-1",
        contenu: "Relevé cadastral commandé. En attente de la réponse de l'Agence Nationale de la Conservation Foncière.",
        createdAt: "2023-01-25",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-004-1",
        nom: "Titre foncier TF-45678.pdf",
        type: "titre_foncier",
        taille: 312000,
        url: "/documents/dos-004/titre-foncier.pdf",
        createdAt: "2023-01-12",
      },
    ],
    audiences: [
      {
        id: "aud-004-1",
        dossierId: "dos-004",
        date: "2023-05-08",
        heure: "14:00",
        tribunal: "TPI Marrakech",
        type: "audience",
        statut: "terminee",
        notes: "Renvoi pour production du rapport de géomètre.",
      },
      {
        id: "aud-004-2",
        dossierId: "dos-004",
        date: "2026-04-23",
        heure: "11:00",
        tribunal: "TPI Marrakech",
        salle: "Salle 7",
        type: "audience",
        statut: "programmee",
        notes: "Plaidoiries au fond.",
      },
    ],
    factures: [],
    createdAt: "2023-01-10",
  },
  {
    id: "dos-005",
    numero: "DOS-2023-005",
    clientId: "cli-005",
    client: mockClients[4],
    partieAdverse: "Chraibi Ahmed (époux)",
    type: "famille",
    tribunal: "TPI Casablanca",
    statut: "en_cours",
    description: "Divorce contentieux. La cliente demande la dissolution du mariage, la garde exclusive des trois enfants mineurs et une pension alimentaire mensuelle.",
    notes: [
      {
        id: "not-005-1",
        contenu: "Violences documentées. Dépôt de plainte au commissariat effectué avant la saisine du tribunal.",
        createdAt: "2023-04-10",
        auteur: "Me. Rachid Amrani",
      },
      {
        id: "not-005-2",
        contenu: "Ordonnance de mesures provisoires rendue : garde provisoire accordée, pension mensuelle fixée à 3 000 MAD.",
        createdAt: "2023-05-22",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-005-1",
        nom: "Acte de mariage.pdf",
        type: "acte_etat_civil",
        taille: 143000,
        url: "/documents/dos-005/acte-mariage.pdf",
        createdAt: "2023-04-05",
      },
    ],
    audiences: [
      {
        id: "aud-005-1",
        dossierId: "dos-005",
        date: "2023-05-15",
        heure: "10:00",
        tribunal: "TPI Casablanca",
        type: "audience",
        statut: "terminee",
        notes: "Ordonnance de mesures provisoires.",
      },
      {
        id: "aud-005-3",
        dossierId: "dos-005",
        date: "2026-04-24",
        heure: "10:00",
        tribunal: "TPI Casablanca",
        salle: "Salle 12",
        type: "audience",
        statut: "programmee",
        notes: "Plaidoiries sur le fond.",
      },
    ],
    factures: [
      {
        id: "fac-005-2",
        numero: "FAC-2023-015",
        dossierId: "dos-005",
        clientId: "cli-005",
        lignes: [
          { id: "lig-005-2-1", description: "Honoraires — phase au fond", quantite: 1, prixUnitaire: 12000 },
        ],
        tva: 20,
        totalHT: 12000,
        totalTTC: 14400,
        statut: "envoyee",
        dateEmission: "2024-01-10",
        dateEcheance: "2024-02-10",
      },
    ],
    createdAt: "2023-04-02",
  },
  {
    id: "dos-006",
    numero: "DOS-2021-006",
    clientId: "cli-006",
    client: mockClients[5],
    partieAdverse: "Coopérative Al Amal",
    type: "commercial",
    tribunal: "TC Casablanca",
    statut: "cloture",
    description: "Litige commercial relatif à un contrat de promotion immobilière. Résolution du contrat pour inexécution et restitution des sommes versées.",
    notes: [
      {
        id: "not-006-1",
        contenu: "Contrat de 4,5 millions MAD non exécuté dans les délais. Mise en demeure envoyée.",
        createdAt: "2021-07-10",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-006-1",
        nom: "Contrat de promotion immobilière.pdf",
        type: "contrat",
        taille: 445000,
        url: "/documents/dos-006/contrat-promotion.pdf",
        createdAt: "2021-06-25",
      },
    ],
    audiences: [
      {
        id: "aud-006-1",
        dossierId: "dos-006",
        date: "2021-11-22",
        heure: "14:30",
        tribunal: "TC Casablanca",
        type: "audience",
        statut: "terminee",
        notes: "Tentative de conciliation. Partie adverse ouverte à une transaction.",
      },
    ],
    factures: [
      {
        id: "fac-006-1",
        numero: "FAC-2021-009",
        dossierId: "dos-006",
        clientId: "cli-006",
        lignes: [
          { id: "lig-006-1-1", description: "Honoraires litige commercial — transaction", quantite: 1, prixUnitaire: 35000 },
          { id: "lig-006-1-2", description: "Frais divers et correspondances", quantite: 1, prixUnitaire: 3000 },
        ],
        tva: 20,
        totalHT: 38000,
        totalTTC: 45600,
        statut: "payee",
        dateEmission: "2022-03-01",
        dateEcheance: "2022-04-01",
      },
    ],
    createdAt: "2021-06-18",
  },
  {
    id: "dos-007",
    numero: "DOS-2022-007",
    clientId: "cli-007",
    client: mockClients[6],
    partieAdverse: "Bensouda Khalid (ex-associé)",
    type: "commercial",
    tribunal: "TC Fès",
    statut: "en_attente",
    description: "Dissolution d'une société en nom collectif et partage de l'actif social. Désaccord sur la valorisation des parts et les créances croisées entre associés.",
    notes: [
      {
        id: "not-007-1",
        contenu: "Expertise comptable ordonnée par le tribunal. En attente du dépôt du rapport.",
        createdAt: "2022-10-05",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-007-1",
        nom: "Statuts de la société.pdf",
        type: "statuts",
        taille: 267000,
        url: "/documents/dos-007/statuts.pdf",
        createdAt: "2022-09-20",
      },
    ],
    audiences: [
      {
        id: "aud-007-1",
        dossierId: "dos-007",
        date: "2022-09-28",
        heure: "09:00",
        tribunal: "TC Fès",
        type: "audience",
        statut: "terminee",
        notes: "Désignation d'un expert comptable judiciaire.",
      },
      {
        id: "aud-007-2",
        dossierId: "dos-007",
        date: "2026-06-10",
        heure: "14:00",
        tribunal: "TC Fès",
        type: "audience",
        statut: "programmee",
        notes: "Audience après dépôt du rapport d'expertise.",
      },
    ],
    factures: [
      {
        id: "fac-007-1",
        numero: "FAC-2022-010",
        dossierId: "dos-007",
        clientId: "cli-007",
        lignes: [
          { id: "lig-007-1-1", description: "Honoraires dissolution de société", quantite: 1, prixUnitaire: 18000 },
        ],
        tva: 20,
        totalHT: 18000,
        totalTTC: 21600,
        statut: "payee",
        dateEmission: "2022-10-01",
        dateEcheance: "2022-11-01",
      },
    ],
    createdAt: "2022-09-14",
  },
  {
    id: "dos-008",
    numero: "DOS-2023-008",
    clientId: "cli-008",
    client: mockClients[7],
    partieAdverse: "Entreprise de BTP Atlas Construction",
    type: "civil",
    tribunal: "TPI Agadir",
    statut: "en_cours",
    description: "Réparation du préjudice subi suite à un accident du travail. Chute de hauteur sur chantier entraînant une invalidité partielle permanente.",
    notes: [
      {
        id: "not-008-1",
        contenu: "Rapport médical confirmant une IPP de 25%. Procédure CNSS parallèle engagée.",
        createdAt: "2023-07-15",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-008-1",
        nom: "Rapport médical IPP.pdf",
        type: "rapport_medical",
        taille: 234000,
        url: "/documents/dos-008/rapport-ipp.pdf",
        createdAt: "2023-07-01",
      },
    ],
    audiences: [
      {
        id: "aud-008-1",
        dossierId: "dos-008",
        date: "2023-11-14",
        heure: "10:30",
        tribunal: "TPI Agadir",
        type: "audience",
        statut: "terminee",
        notes: "Renvoi pour expertise médicale complémentaire.",
      },
      {
        id: "aud-008-2",
        dossierId: "dos-008",
        date: "2026-05-28",
        heure: "09:00",
        tribunal: "TPI Agadir",
        type: "audience",
        statut: "programmee",
      },
    ],
    factures: [],
    createdAt: "2023-06-28",
  },
  {
    id: "dos-009",
    numero: "DOS-2023-009",
    clientId: "cli-009",
    client: mockClients[8],
    partieAdverse: "Fournisseur Chimie Verte SARL",
    type: "commercial",
    tribunal: "TC Beni Mellal",
    statut: "en_attente",
    description: "Litige commercial pour livraison non conforme d'engrais ayant causé des pertes agricoles significatives. Demande de résolution du contrat et indemnisation.",
    notes: [
      {
        id: "not-009-1",
        contenu: "Analyse en laboratoire confirmant la non-conformité des produits livrés. Rapport joint au dossier.",
        createdAt: "2023-03-05",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-009-1",
        nom: "Contrat de fourniture.pdf",
        type: "contrat",
        taille: 189000,
        url: "/documents/dos-009/contrat-fourniture.pdf",
        createdAt: "2023-02-28",
      },
    ],
    audiences: [
      {
        id: "aud-009-1",
        dossierId: "dos-009",
        date: "2023-08-22",
        heure: "11:00",
        tribunal: "TC Beni Mellal",
        type: "audience",
        statut: "terminee",
        notes: "Jonction d'une expertise agricole.",
      },
      {
        id: "aud-009-2",
        dossierId: "dos-009",
        date: "2026-06-12",
        heure: "10:00",
        tribunal: "TC Beni Mellal",
        type: "delibere",
        statut: "programmee",
      },
    ],
    factures: [
      {
        id: "fac-009-1",
        numero: "FAC-2023-007",
        dossierId: "dos-009",
        clientId: "cli-009",
        lignes: [
          { id: "lig-009-1-1", description: "Honoraires litige commercial agricole", quantite: 1, prixUnitaire: 14000 },
        ],
        tva: 20,
        totalHT: 14000,
        totalTTC: 16800,
        statut: "brouillon",
        dateEmission: "2023-06-01",
        dateEcheance: "2023-07-01",
      },
    ],
    createdAt: "2023-02-19",
  },
  {
    id: "dos-010",
    numero: "DOS-2023-010",
    clientId: "cli-010",
    client: mockClients[9],
    partieAdverse: "Parquet du TPI de Casablanca",
    type: "penal",
    tribunal: "TPI Casablanca",
    statut: "en_cours",
    description: "Poursuite pénale pour détournement de fonds présumé. Le client nie les faits. Constitution de partie civile de la société plaignante.",
    notes: [
      {
        id: "not-010-1",
        contenu: "Client placé sous contrôle judiciaire. Interdiction de quitter le territoire. Caution versée.",
        createdAt: "2023-08-20",
        auteur: "Me. Rachid Amrani",
      },
      {
        id: "not-010-2",
        contenu: "Mémoire de défense déposé. Alibi solide pour les dates des faits allégués.",
        createdAt: "2023-10-05",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-010-1",
        nom: "Procès-verbal d'audition.pdf",
        type: "pv_audition",
        taille: 267000,
        url: "/documents/dos-010/pv-audition.pdf",
        createdAt: "2023-08-15",
      },
    ],
    audiences: [
      {
        id: "aud-010-1",
        dossierId: "dos-010",
        date: "2023-12-05",
        heure: "09:00",
        tribunal: "TPI Casablanca",
        type: "audience",
        statut: "terminee",
        notes: "Renvoi pour complément d'instruction.",
      },
      {
        id: "aud-010-2",
        dossierId: "dos-010",
        date: "2026-05-06",
        heure: "14:00",
        tribunal: "TPI Casablanca",
        salle: "Chambre correctionnelle 3",
        type: "audience",
        statut: "programmee",
        notes: "Plaidoiries.",
      },
    ],
    factures: [
      {
        id: "fac-010-1",
        numero: "FAC-2023-011",
        dossierId: "dos-010",
        clientId: "cli-010",
        lignes: [
          { id: "lig-010-1-1", description: "Honoraires défense pénale — phase d'instruction", quantite: 1, prixUnitaire: 25000 },
          { id: "lig-010-1-2", description: "Provision sur honoraires de plaidoirie", quantite: 1, prixUnitaire: 15000 },
        ],
        tva: 20,
        totalHT: 40000,
        totalTTC: 48000,
        statut: "en_retard",
        dateEmission: "2023-09-01",
        dateEcheance: "2023-10-01",
      },
    ],
    createdAt: "2023-08-07",
  },
  {
    id: "dos-011",
    numero: "DOS-2024-011",
    clientId: "cli-011",
    client: mockClients[10],
    partieAdverse: "Société de Gardiennage SecurMax",
    type: "civil",
    tribunal: "TPI Casablanca",
    statut: "en_cours",
    description: "Licenciement abusif d'une agente de sécurité après 8 ans d'ancienneté. Demande de réintégration ou d'indemnités de licenciement majorées.",
    notes: [
      {
        id: "not-011-1",
        contenu: "Lettre de licenciement insuffisamment motivée selon les critères du Code du travail.",
        createdAt: "2024-01-25",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-011-1",
        nom: "Lettre de licenciement.pdf",
        type: "lettre_licenciement",
        taille: 98000,
        url: "/documents/dos-011/lettre-licenciement.pdf",
        createdAt: "2024-01-15",
      },
    ],
    audiences: [
      {
        id: "aud-011-1",
        dossierId: "dos-011",
        date: "2024-06-17",
        heure: "10:00",
        tribunal: "TPI Casablanca",
        type: "audience",
        statut: "terminee",
        notes: "Première audience. Renvoi pour échange de conclusions.",
      },
      {
        id: "aud-011-2",
        dossierId: "dos-011",
        date: "2026-05-19",
        heure: "11:30",
        tribunal: "TPI Casablanca",
        salle: "Section sociale",
        type: "audience",
        statut: "programmee",
      },
    ],
    factures: [],
    createdAt: "2024-01-15",
  },
  {
    id: "dos-012",
    numero: "DOS-2024-012",
    clientId: "cli-012",
    client: mockClients[11],
    partieAdverse: "WebSolutions Maroc (prestataire IT)",
    type: "commercial",
    tribunal: "TC Casablanca",
    statut: "en_attente",
    description: "Litige contractuel avec un prestataire informatique ayant livré une plateforme non conforme aux spécifications techniques. Demande de résolution et de remboursement.",
    notes: [
      {
        id: "not-012-1",
        contenu: "Cahier des charges non respecté. Audit technique réalisé par un expert indépendant.",
        createdAt: "2024-04-10",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-012-1",
        nom: "Cahier des charges.pdf",
        type: "cahier_charges",
        taille: 567000,
        url: "/documents/dos-012/cahier-charges.pdf",
        createdAt: "2024-03-28",
      },
    ],
    audiences: [
      {
        id: "aud-012-1",
        dossierId: "dos-012",
        date: "2026-06-04",
        heure: "09:30",
        tribunal: "TC Casablanca",
        type: "audience",
        statut: "programmee",
        notes: "Première audience.",
      },
    ],
    factures: [
      {
        id: "fac-012-1",
        numero: "FAC-2024-005",
        dossierId: "dos-012",
        clientId: "cli-012",
        lignes: [
          { id: "lig-012-1-1", description: "Honoraires litige IT — phase précontentieux", quantite: 1, prixUnitaire: 7500 },
        ],
        tva: 20,
        totalHT: 7500,
        totalTTC: 9000,
        statut: "envoyee",
        dateEmission: "2024-05-01",
        dateEcheance: "2024-06-01",
      },
    ],
    createdAt: "2024-03-22",
  },
  {
    id: "dos-013",
    numero: "DOS-2021-013",
    clientId: "cli-006",
    client: mockClients[5],
    partieAdverse: "Entreprise de Construction Bâtir SA",
    type: "commercial",
    tribunal: "TC Rabat",
    statut: "cloture",
    description: "Contentieux lié à des malfaçons constatées dans la construction d'un immeuble résidentiel. Mise en cause de la responsabilité décennale du constructeur.",
    notes: [
      {
        id: "not-013-1",
        contenu: "Expertise judiciaire confirmant les désordres structurels. Évaluation du préjudice à 2,8 millions MAD.",
        createdAt: "2022-04-20",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-013-1",
        nom: "Rapport d'expertise malfaçons.pdf",
        type: "rapport_expertise",
        taille: 678000,
        url: "/documents/dos-013/rapport-malfacons.pdf",
        createdAt: "2022-04-15",
      },
    ],
    audiences: [
      {
        id: "aud-013-1",
        dossierId: "dos-013",
        date: "2022-06-08",
        heure: "09:00",
        tribunal: "TC Rabat",
        type: "audience",
        statut: "terminee",
      },
      {
        id: "aud-013-3",
        dossierId: "dos-013",
        date: "2023-03-12",
        heure: "10:00",
        tribunal: "TC Rabat",
        type: "prononce",
        statut: "terminee",
        notes: "Jugement prononcé. Appel non interjeté. Exécutoire.",
      },
    ],
    factures: [],
    createdAt: "2021-09-01",
  },
  {
    id: "dos-014",
    numero: "DOS-2022-014",
    clientId: "cli-001",
    client: mockClients[0],
    partieAdverse: "M. Cherif (locataire commercial)",
    type: "civil",
    tribunal: "TPI Casablanca",
    statut: "cloture",
    description: "Procédure d'expulsion d'un locataire commercial pour non-paiement de loyers. Récupération des arriérés de loyers et libération des locaux.",
    notes: [
      {
        id: "not-014-1",
        contenu: "18 mois d'arriérés. Commandement de payer signifié. Délai expiré sans paiement.",
        createdAt: "2022-05-12",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-014-1",
        nom: "Bail commercial.pdf",
        type: "contrat",
        taille: 234000,
        url: "/documents/dos-014/bail-commercial.pdf",
        createdAt: "2022-05-10",
      },
    ],
    audiences: [
      {
        id: "aud-014-2",
        dossierId: "dos-014",
        date: "2022-09-27",
        heure: "10:00",
        tribunal: "TPI Casablanca",
        type: "prononce",
        statut: "terminee",
        notes: "Ordonnance d'expulsion rendue.",
      },
    ],
    factures: [],
    createdAt: "2022-05-01",
  },
  {
    id: "dos-015",
    numero: "DOS-2024-015",
    clientId: "cli-012",
    client: mockClients[11],
    partieAdverse: "CNDP (Protection des données personnelles)",
    type: "administratif",
    tribunal: "TA Rabat",
    statut: "en_cours",
    description: "Recours contre une mise en demeure de la CNDP pour violation présumée de la loi 09-08 sur la protection des données personnelles. Régularisation et contestation des sanctions.",
    notes: [
      {
        id: "not-015-1",
        contenu: "Mise en demeure reçue suite à une plainte d'un utilisateur. Délai de régularisation de 30 jours.",
        createdAt: "2024-04-01",
        auteur: "Me. Rachid Amrani",
      },
    ],
    documents: [
      {
        id: "doc-015-1",
        nom: "Mise en demeure CNDP.pdf",
        type: "decision_administrative",
        taille: 178000,
        url: "/documents/dos-015/mise-en-demeure-cndp.pdf",
        createdAt: "2024-03-28",
      },
    ],
    audiences: [
      {
        id: "aud-015-1",
        dossierId: "dos-015",
        date: "2026-06-17",
        heure: "10:00",
        tribunal: "TA Rabat",
        type: "audience",
        statut: "programmee",
        notes: "Première audience sur recours.",
      },
    ],
    factures: [
      {
        id: "fac-015-1",
        numero: "FAC-2024-007",
        dossierId: "dos-015",
        clientId: "cli-012",
        lignes: [
          { id: "lig-015-1-1", description: "Conseil et mise en conformité RGPD", quantite: 1, prixUnitaire: 15000 },
          { id: "lig-015-1-2", description: "Honoraires recours administratif CNDP", quantite: 1, prixUnitaire: 12000 },
        ],
        tva: 20,
        totalHT: 27000,
        totalTTC: 32400,
        statut: "envoyee",
        dateEmission: "2024-05-15",
        dateEcheance: "2024-06-15",
      },
    ],
    createdAt: "2024-03-22",
  },
];
